import React from "react";
import Head from "next/head";
import style from "../styles/layout.module.css"
import Menu from "./menu";

function Layout({children,title}) {
    return(
        <div>
            <Head>
            <title>Git Hub Merch {title?`| ${title}`:''}</title>
            <meta name="description" content="Generated by create next app" />
        </Head>
            <Menu/>
            <div className={style.container}>{children}</div>
        </div>

    )

}
export default Layout;